import os
from pathlib import Path
from collections.abc import Iterator

_ABSENT_ENTRY_ERRNOS: frozenset[int]
_ABSENT_ENTRY_WINERRORS: frozenset[int]

def walk_directory(directory: Path) -> list[Path]: ...
def walk_files(directory: Path) -> list[Path]: ...
def discover_marker_files(directory: Path, marker_name: str) -> list[Path]: ...
def discover_marker_roots(directory: Path, marker_name: str, levels_up: int = 0) -> list[Path]: ...
def resolve_unique_roots(paths: list[Path] | tuple[Path, ...]) -> tuple[Path, ...]: ...
def reports_absent_entry(error: OSError) -> bool: ...
def _scan_tree(directory: Path) -> Iterator[os.DirEntry[str]]: ...
def _resolves_to_file(entry: os.DirEntry[str]) -> bool: ...
def _extract_unique_components(paths: list[Path]) -> tuple[str, ...]: ...
