from enum import IntEnum, StrEnum
from typing import Any, Self
from pathlib import Path
from contextlib import contextmanager
from dataclasses import field, dataclass
from collections.abc import Mapping, Iterator

from ..processing import discover_marker_files as discover_marker_files
from .yaml_config import (
    YAML_EXCLUDE_METADATA as YAML_EXCLUDE_METADATA,
    YamlConfig as YamlConfig,
)

_SCHEDULER_EXECUTOR_SOURCES: tuple[tuple[str, tuple[str, ...], str | None], ...]
_LOCK_ACQUISITION_TIMEOUT: float

class ProcessingStatus(IntEnum):
    SCHEDULED = 0
    RUNNING = 1
    SUCCEEDED = 2
    FAILED = 3

class TrackerStatus(StrEnum):
    NOT_STARTED = "not_started"
    IN_PROGRESS = "in_progress"
    PROCESSING = "processing"
    COMPLETED = "completed"
    FAILED = "failed"

@dataclass(slots=True)
class JobState:
    job_name: str
    specifier: str = ...
    status: ProcessingStatus = ...
    executor_id: str | None = ...
    error_message: str | None = ...
    started_at: int | None = ...
    completed_at: int | None = ...

@dataclass
class ProcessingTracker(YamlConfig):
    file_path: Path = field(metadata=YAML_EXCLUDE_METADATA)
    jobs: dict[str, JobState] = field(default_factory=dict)
    lock_path: str = field(init=False, metadata=YAML_EXCLUDE_METADATA)
    def __post_init__(self) -> None: ...
    @classmethod
    def restore_excluded_fields(cls, data: dict[Any, Any], file_path: Path) -> dict[Any, Any]: ...
    @classmethod
    def discover(cls, root_directory: Path, tracker_name: str) -> list[Self]: ...
    @staticmethod
    def generate_job_id(job_name: str, specifier: str = "") -> str: ...
    @staticmethod
    def resolve_status(summary: Mapping[str, int]) -> TrackerStatus: ...
    def initialize_jobs(self, jobs: list[tuple[str, str]]) -> list[str]: ...
    def align_jobs(self, jobs: list[tuple[str, str]], universe: list[tuple[str, str]] | None = None) -> list[str]: ...
    def resolve_job(self, job_id: str, universe: list[tuple[str, str]]) -> tuple[str, str]: ...
    def snapshot(self) -> dict[str, JobState]: ...
    def summarize(self) -> dict[str, Any]: ...
    def find_jobs(self, job_name: str | None = None, specifier: str | None = None) -> dict[str, tuple[str, str]]: ...
    @contextmanager
    def run_job(self, job_id: str, executor_id: str | None = None) -> Iterator[None]: ...
    def start_job(self, job_id: str, executor_id: str | None = None) -> None: ...
    def complete_job(self, job_id: str) -> None: ...
    def fail_job(self, job_id: str, error_message: str | None = None) -> None: ...
    def get_job_status(self, job_id: str) -> ProcessingStatus: ...
    def reset(self) -> None: ...
    @property
    def complete(self) -> bool: ...
    @property
    def encountered_error(self) -> bool: ...
    def get_jobs_by_status(self, status: ProcessingStatus | str) -> list[str]: ...
    def get_summary(self) -> dict[ProcessingStatus, int]: ...
    def get_job_info(self, job_id: str) -> JobState: ...
    def reset_jobs(self, job_ids: list[str]) -> list[str]: ...
    def retry_failed_jobs(self) -> list[str]: ...
    @staticmethod
    def _resolve_executor_id() -> str: ...
    def _load_state(self, *, create_missing: bool = True) -> None: ...
    def _save_state(self) -> None: ...
