from enum import IntEnum
from pathlib import Path
from dataclasses import field, dataclass

from .yaml_config import YamlConfig as YamlConfig

class ProcessingStatus(IntEnum):
    SCHEDULED = 0
    RUNNING = 1
    SUCCEEDED = 2
    FAILED = 3

@dataclass(slots=True)
class JobState:
    job_name: str
    specifier: str = ...
    status: ProcessingStatus = ...
    executor_id: str | None = ...
    error_message: str | None = ...
    started_at: int | None = ...
    completed_at: int | None = ...

@dataclass
class ProcessingTracker(YamlConfig):
    file_path: Path
    jobs: dict[str, JobState] = field(default_factory=dict)
    lock_path: str = field(init=False)
    def __post_init__(self) -> None: ...
    @staticmethod
    def generate_job_id(job_name: str, specifier: str = "") -> str: ...
    def _load_state(self) -> None: ...
    def _save_state(self) -> None: ...
    def initialize_jobs(self, jobs: list[tuple[str, str]]) -> list[str]: ...
    def find_jobs(self, job_name: str | None = None, specifier: str | None = None) -> dict[str, tuple[str, str]]: ...
    def start_job(self, job_id: str, executor_id: str | None = None) -> None: ...
    def complete_job(self, job_id: str) -> None: ...
    def fail_job(self, job_id: str, error_message: str | None = None) -> None: ...
    def get_job_status(self, job_id: str) -> ProcessingStatus: ...
    def reset(self) -> None: ...
    @property
    def complete(self) -> bool: ...
    @property
    def encountered_error(self) -> bool: ...
    def get_jobs_by_status(self, status: ProcessingStatus | str) -> list[str]: ...
    def get_summary(self) -> dict[ProcessingStatus, int]: ...
    def get_job_info(self, job_id: str) -> JobState: ...
    def retry_failed_jobs(self) -> list[str]: ...
