from typing import Any, Self
from pathlib import Path
from dataclasses import dataclass
from collections.abc import Callable as Callable

def _serialize_value(value: Any) -> Any: ...
def _make_union_enum_hook(enum_types: list[type]) -> Callable[[Any], Any]: ...
def _collect_type_hooks(cls) -> dict[Any, Callable[[Any], Any]]: ...

@dataclass
class YamlConfig:
    def to_yaml(self, file_path: Path) -> None: ...
    @classmethod
    def from_yaml(cls, file_path: Path) -> Self: ...
