"""Provides the LogArchiveReader class for efficiently reading and iterating through .npz log archives generated by
DataLogger instances, together with the functions that discover those archives on disk.
"""

from __future__ import annotations

from math import ceil
from typing import TYPE_CHECKING
from functools import cached_property
from dataclasses import dataclass

import numpy as np
from ataraxis_base_utilities import console, resolve_worker_count

from ..processing import discover_marker_files
from .serialized_data_logger import LOG_ARCHIVE_SUFFIX

if TYPE_CHECKING:
    from pathlib import Path
    from collections.abc import Iterator

    from numpy.typing import NDArray

PARALLEL_PROCESSING_THRESHOLD: int = 2000
"""The number of data messages a log archive has to hold before its messages are worth processing in parallel.

Notes:
    An archive holding fewer messages costs more in worker startup and message transfer than the parallel decode
    saves, so ``LogArchiveReader.get_batches()`` stops dividing such an archive and hands back every message it holds
    as one batch.
"""

_TIMESTAMP_BYTE_SIZE: int = 8
"""The number of bytes used to store the timestamp in each message header."""

_ONSET_KEY_SUFFIX: str = "_00000000000000000000"
"""The suffix pattern for onset message keys (underscore + 20 zeros for timestamp=0)."""


@dataclass(frozen=True, slots=True)
class LogMessage:
    """Stores a single message extracted from a log archive.

    Notes:
        The structure of the payload is domain-specific and must be parsed by the consumer.
    """

    timestamp_us: np.uint64
    """The absolute UTC timestamp of when the message was logged, in microseconds since epoch."""

    payload: NDArray[np.uint8]
    """The message payload as a byte array."""


def find_log_archive(log_directory: Path, source_id: str) -> Path:
    """Searches for the single log archive holding the entries of the target source under the log directory.

    Notes:
        The whole tree beneath the log directory is searched, so an archive nested at any depth is found. A source
        writes one archive per logger output directory, so a tree holding several matches spans several loggers and
        is ambiguous rather than merely redundant.

    Args:
        log_directory: The root directory whose tree is searched.
        source_id: The identifier of the source whose archive is resolved, matching the archive filename ahead of the
            log archive suffix.

    Returns:
        The path to the discovered log archive.

    Raises:
        FileNotFoundError: If the log directory does not exist, is not a directory, or holds no archive for the
            requested source.
        OSError: If any directory beneath the log directory cannot be read.
        ValueError: If the log directory holds more than one archive for the requested source.
    """
    if not log_directory.is_dir():
        message = (
            f"Unable to find the log archive of source '{source_id}' in '{log_directory}'. The path does not exist "
            f"or is not a directory."
        )
        console.error(message=message, error=FileNotFoundError)

    archive_name = f"{source_id}{LOG_ARCHIVE_SUFFIX}"
    matches = discover_marker_files(directory=log_directory, marker_name=archive_name)

    if not matches:
        message = (
            f"Unable to find the log archive of source '{source_id}' in '{log_directory}'. No file named "
            f"'{archive_name}' was found anywhere under the directory."
        )
        console.error(message=message, error=FileNotFoundError)

    if len(matches) > 1:
        message = (
            f"Unable to find the log archive of source '{source_id}' in '{log_directory}'. Exactly one file named "
            f"'{archive_name}' must exist under the directory, but {len(matches)} were found: "
            f"{[str(match) for match in matches]}."
        )
        console.error(message=message, error=ValueError)

    return matches[0]


def discover_log_archives(log_directory: Path) -> dict[str, Path]:
    """Discovers every log archive stored directly inside the target logger output directory.

    Notes:
        Only the directory's own entries are inspected, since one logger writes every archive it assembles side by
        side. Searching a tree that spans several loggers instead resolves each source with ``find_log_archive()``.

    Args:
        log_directory: The logger output directory whose archives are discovered.

    Returns:
        The path to every discovered archive, keyed by the identifier of the source that produced it.

    Raises:
        FileNotFoundError: If the log directory does not exist or is not a directory.
    """
    if not log_directory.is_dir():
        message = (
            f"Unable to discover the log archives stored in '{log_directory}'. The path does not exist or is not a "
            f"directory."
        )
        console.error(message=message, error=FileNotFoundError)

    return {
        source_id: archive_path
        for archive_path in sorted(log_directory.glob(f"*{LOG_ARCHIVE_SUFFIX}"))
        if archive_path.is_file() and (source_id := archive_path.name.removesuffix(LOG_ARCHIVE_SUFFIX))
    }


def read_archive_message_count(archive_path: Path) -> int:
    """Reads the number of data messages the target log archive holds without decoding any of them.

    Notes:
        Reads the archive's zip directory alone, so the cost tracks the number of messages rather than their size.

    Args:
        archive_path: The path to the .npz log archive to read.

    Returns:
        The number of data messages the archive holds, excluding the onset message.

    Raises:
        FileNotFoundError: If the archive does not exist or is not a file.
    """
    if not archive_path.is_file():
        message = (
            f"Unable to read the message count of the log archive at '{archive_path}'. The path does not exist or is "
            f"not a file."
        )
        console.error(message=message, error=FileNotFoundError)

    with np.load(file=archive_path, allow_pickle=False) as archive:
        return sum(1 for key in archive.files if not key.endswith(_ONSET_KEY_SUFFIX))


class LogArchiveReader:
    """Reads and iterates through .npz log archives generated by DataLogger instances.

    Notes:
        Each .npz archive contains messages from a single source (producer). Messages are stored with the structure:
        [source_id (1 byte)][timestamp (8 bytes)][payload (N bytes)].

        The first message with a timestamp value of 0 contains the onset timestamp as its payload. This onset timestamp
        is the UTC epoch reference used to convert elapsed microseconds to absolute timestamps.

    Args:
        archive_path: The path to the .npz log archive file to read.
        onset_us: The pre-discovered onset timestamp in microseconds since epoch. If provided, skips onset discovery.

    Attributes:
        _archive_path: Stores the path to the log archive file.
        _onset_us: Stores the onset timestamp if pre-provided.
        _message_keys: Caches the list of message keys (excluding the onset message).

    Raises:
        FileNotFoundError: If the specified archive file does not exist.
        ValueError: If the archive lacks a valid onset timestamp message when the onset timestamp is accessed.
    """

    def __init__(self, archive_path: Path, onset_us: np.uint64 | None = None) -> None:
        if not archive_path.exists():
            message = f"Unable to open log archive. The file does not exist at the expected path: {archive_path}."
            console.error(message=message, error=FileNotFoundError)

        self._archive_path: Path = archive_path
        self._onset_us: np.uint64 | None = onset_us
        self._message_keys: list[str] | None = None

    def __repr__(self) -> str:
        """Returns the string representation of the LogArchiveReader instance."""
        onset_string = str(self._onset_us) if self._onset_us is not None else "not discovered"
        return f"LogArchiveReader(archive_path={self._archive_path}, onset_us={onset_string})"

    @cached_property
    def onset_timestamp_us(self) -> np.uint64:
        """Returns the onset timestamp in microseconds since epoch, taken from the pre-provided value when available
        or discovered by scanning the archive for the first message with a timestamp of 0.

        Raises:
            ValueError: If the archive does not contain a valid onset timestamp message.
        """
        if self._onset_us is not None:
            return self._onset_us

        with np.load(file=self._archive_path, allow_pickle=False, mmap_mode="r") as archive:
            file_list = list(archive.files)

            for number, file_key in enumerate(file_list):
                message_bytes: NDArray[np.uint8] = archive[file_key]

                # The timestamp occupies bytes 1-9 (8 bytes after the 1-byte source_id).
                timestamp_value = message_bytes[1 : 1 + _TIMESTAMP_BYTE_SIZE].view(np.uint64).item()

                # A timestamp value of 0 indicates the onset message.
                if timestamp_value == 0:
                    # The payload contains the onset timestamp as an unsigned 64-bit integer.
                    onset = np.uint64(message_bytes[1 + _TIMESTAMP_BYTE_SIZE :].view(np.uint64).item())

                    self._message_keys = file_list[number + 1 :]

                    return onset

        message = (
            f"Unable to discover onset timestamp in log archive. The archive must contain a message with timestamp "
            f"value 0 storing the UTC epoch reference, but none was found in: {self._archive_path}."
        )
        console.error(message=message, error=ValueError)
        # Unreachable: console.error() is NoReturn, but ruff cannot trace NoReturn through method calls (RET503).
        return np.uint64(0)  # pragma: no cover

    @property
    def message_count(self) -> int:
        """Returns the number of data messages in the archive, excluding the onset message."""
        return len(self._get_message_keys())

    def get_batches(self, workers: int = -1, batch_multiplier: int = 4) -> list[list[str]]:
        """Divides message keys into batches optimized for parallel processing.

        Notes:
            Uses over-batching (creating more batches than workers) to improve load balancing when message processing
            times vary. The ``batch_multiplier`` parameter controls the degree of over-batching.

            For archives with fewer messages than ``PARALLEL_PROCESSING_THRESHOLD``, returns a single batch containing
            all message keys, or an empty list when the archive contains no data messages.

        Args:
            workers: The number of worker processes to optimize batching for. A value less than 1 uses all available
                CPU cores minus 2.
            batch_multiplier: The over-batching factor. Creates up to (workers * batch_multiplier) batches for better
                load distribution.

        Returns:
            The message key batches, each of which is accepted as the keys argument of iter_messages().
        """
        keys = self._get_message_keys()
        total_messages = len(keys)

        if total_messages < PARALLEL_PROCESSING_THRESHOLD:
            return [keys] if keys else []

        resolved_workers = resolve_worker_count(requested_workers=max(0, workers))

        batch_size = max(1, ceil(total_messages / (resolved_workers * batch_multiplier)))

        return [keys[start_index : start_index + batch_size] for start_index in range(0, total_messages, batch_size)]

    def iter_messages(self, keys: list[str] | None = None) -> Iterator[LogMessage]:
        """Iterates through messages in the archive, yielding LogMessage instances.

        Notes:
            Opens the archive once and keeps it open for the duration of iteration, decoding each requested entry on
            access.

            If ``keys`` is provided, only iterates through the specified messages.

        Args:
            keys: The message keys to iterate. If None, iterates through every data message in the archive.

        Yields:
            LogMessage instances containing the absolute timestamp and payload for each message.
        """
        onset = self.onset_timestamp_us

        target_keys = keys if keys is not None else self._get_message_keys()

        # The header width is the same for every message, so it is resolved once rather than per message.
        header_size = 1 + _TIMESTAMP_BYTE_SIZE

        with np.load(file=self._archive_path, allow_pickle=False, mmap_mode="r") as archive:
            for key in target_keys:
                message: NDArray[np.uint8] = archive[key]

                elapsed_us = message[1:header_size].view(np.uint64).item()

                absolute_timestamp = onset + elapsed_us

                payload = message[header_size:].copy()

                yield LogMessage(timestamp_us=np.uint64(absolute_timestamp), payload=payload)

    def read_all_messages(self) -> tuple[NDArray[np.uint64], list[NDArray[np.uint8]]]:
        """Reads all messages from the archive and returns them as arrays.

        Notes:
            Loads every message into memory at once.

        Returns:
            The absolute message timestamps in microseconds, paired with a list of the per-message payload arrays.
        """
        # Preallocates the timestamp array and fills it by index, so the timestamps never exist as a list of boxed
        # NumPy scalars. The count is free, since message_count reuses the memoized key list iter_messages also reads.
        timestamps: NDArray[np.uint64] = np.empty(shape=self.message_count, dtype=np.uint64)
        payloads: list[NDArray[np.uint8]] = []

        for index, message in enumerate(self.iter_messages()):
            timestamps[index] = message.timestamp_us
            payloads.append(message.payload)

        return timestamps, payloads

    def _get_message_keys(self) -> list[str]:
        """Returns the cached list of message keys, loading and filtering if necessary.

        Notes:
            When onset was pre-provided (skipping discovery), finds the onset key by its filename pattern (ends with
            20 zeros for timestamp=0), then slices from that index.

        Returns:
            The data-message keys, excluding the onset message.
        """
        if self._message_keys is None:
            # Triggers onset discovery which populates _message_keys via slicing.
            _ = self.onset_timestamp_us

            if self._message_keys is None:
                with np.load(file=self._archive_path, allow_pickle=False, mmap_mode="r") as archive:
                    all_keys = list(archive.files)

                    for index, key in enumerate(all_keys):
                        if key.endswith(_ONSET_KEY_SUFFIX):
                            self._message_keys = all_keys[index + 1 :]
                            break
                    else:
                        self._message_keys = all_keys

        return self._message_keys
